### ISSUE TITLE
新版会报错

### ISSUE THREAD

**Issue by q626389190** [jarjin/LuaFramework_UGUI#12]
之前使用2016-04-17，可以正常编译apk.
新版编译apk时提示"Assets/LuaFramework/ToLua/Source/Generate/UnityEngine_InputWrap.cs(259,52): error CS0117: `UnityEngine.Input' does not contain a definition for `IsJoystickPreconfigured'"

**Comment by jarjin** [comment]
unity什么版本？

**Comment by q626389190** [comment]
5.4.1f1 破解了

**Comment by jarjin** [comment]
更新最新版，刚刚修复提交
