### ISSUE TITLE
there are some errors in unity5.5.1f1(64bit) when i use it

### ISSUE THREAD

**Issue by Lofert** [jarjin/LuaFramework_UGUI#15]
Hello, i wander why i use it in unity5.5.1f1(64bit), there will be some errors. How to solve it?

![image](https://cloud.githubusercontent.com/assets/20968233/24661519/290de340-1985-11e7-82a6-ea330d13d35f.png)

Thank you!

**Comment by zhjunlang** [comment]
1.Create a folder named debug at Assets\LuaFramework\Lua\3rd
2.open "using UnityEngine.SceneManagement;" at LuaClient.cs

**Comment by jarjin** [comment]
更新最新版，刚刚修复提交
