### ISSUE TITLE
Uniyt5.6.0   LuaFramwork/Build xxx Resource 有这个错误，无法接着往下运行。

### ISSUE THREAD

**Issue by zhousong3333** [jarjin/LuaFramework_UGUI#18]
Assets/LuaFramework/ToLua/Source/Generate/UnityEngine_LightWrap.cs(617,43): error CS1061: Type `UnityEngine.Light' does not contain a definition for `lightmapBakeType' and no extension method `lightmapBakeType' of type `UnityEngine.Light' could be found. Are you missing an assembly reference?

**Comment by Mary98** [comment]
I have also encountered this problem.

**Comment by jarjin** [comment]
我回家看看，

**Comment by jarjin** [comment]
更新最新版，刚刚修复提交
