### ISSUE TITLE
Sproto疑问

### ISSUE THREAD

**Issue by zxhot007** [jarjin/LuaFramework_UGUI#25]
用了你更新的Plugins，加载SPROTO就报错了 。麻烦看看

**Comment by zernmal** [comment]
我这边也是，打包的 IOS 和 Android 包都不能正常使用了, 求帮忙解决一下

**Comment by jarjin** [comment]
好的，我下班回家看看

**Comment by jarjin** [comment]
重新编译最新版sproto，请替换对应目录即可。
