### ISSUE TITLE
strict.lua没有效果

### ISSUE THREAD

**Issue by rekcah1986** [jarjin/LuaFramework_UGUI#28]
--require "misc.strict"
解开这句没有效果，仍然可以不声明全局变量而直接使用，我理解错了吗？

**Comment by rekcah1986** [comment]
我换了一个新版的可以用了，附上链接
https://stevedonovan.github.io/Penlight/api/source/strict.lua.html

**Comment by jarjin** [comment]
多谢，我更新下
