### ISSUE TITLE
tolua.lua: cannot load incompatible bytecode

### ISSUE THREAD

**Issue by fantao963** [jarjin/LuaFramework_UGUI#31]
public const bool ExampleMode = true;                       //例子模式 

        /// <summary>
        /// 如果开启更新模式，前提必须启动框架自带服务器端。
        /// 否则就需要自己将StreamingAssets里面的所有内容
        /// 复制到自己的Webserver上面，并修改下面的WebUrl。
        /// </summary>
        public const bool UpdateMode = false;                       //更新模式-默认关闭 
        public const bool LuaByteMode = true;                       //Lua字节码模式-默认关闭 
        public const bool LuaBundleMode = true;                    //Lua代码AssetBundle模式

把 LuaByteMode 设置为true时,打包到手机上不能运行
报错 tolua.lua: cannot load incompatible bytecode

**Comment by atgczcl** [comment]
同求为什么，我也遇到这个问题，

**Comment by jarjin** [comment]
这个问题太多人问，其实很简单，我统一回复下，就是大家做游戏，要了解安卓平台是多少位的（32），iOS区分32/64，你给lua虚拟机不同的bytecode，但是你给lua虚拟机的并不是它当下所在平台的模式，自然会报错，因为这块作为一个程序员来说势必要了解，否则你怎么处理iOS的多平台，对吧？

**Comment by jarjin** [comment]
这个问题太多人问，其实很简单，我统一回复下，就是大家做游戏，要了解安卓平台是多少位的（32），iOS区分32/64，你塞给lua虚拟机的bytecode并不是它当下所在平台的模式，自然会报错，因为这块作为一个程序员来说势必要了解，否则你怎么处理iOS的多平台，对吧？解决方法也很简单，就是不同的版本的luavm已经被集成在tolua/ulua里面，你只需要生成相应平台的bytecode即可。安卓就生成32位的，iOS区分两套bytecode，然后给luavm相应的，保证不再报错。
