### ISSUE TITLE
关于ByteBuffer的WriteString方法的一些疑问，如果看到请解答下，谢谢。

### ISSUE THREAD

**Issue by klkucan** [jarjin/LuaFramework_UGUI#33]
@jarjin WriteString方法中会将string转化成的bytes的长度写入stream变量，但是在SocketClient的WriteMessage的方法中会对传入的byte[]组参数再次取长度写入Network stream。这个byte[]本质还是ByteBuffer的stream，这样的话不是对string类型的参数重复写长度了吗？对于服务器来说只要解析开始的长度，然后取字符串长度即可，但是现在这个字符串会的开头会带上一个字符串本身程度的数字，请问是不是bug？

PS：顺便问下LuaClient这个类是不是不再使用了？

**Comment by GPSGH** [comment]
follow Issues

**Comment by jarjin** [comment]
WriteString写长度是为了ReadString的时候方便拿长度，常规做法还有定长结构或者0结尾，这只是我自己喜欢的一种方式。WriteMessage的写长度是整个数据体的长度，一个数据体不可能只包含一个String，不是一个概念。LuaClient在框架中未使用。
