### ISSUE TITLE
当AppConst.LuaByteMode = true & LuaBundleMode = true时，报数据越界

### ISSUE THREAD

**Issue by wangzongyi** [jarjin/LuaFramework_UGUI#40]
LuaException: Array index is out of range.
stack traceback:
	[C]: in function 'print'
	tolua.lua: in function <tolua.lua:0>
LuaInterface.ToLua:Print(IntPtr) (at Assets/LuaFramework/ToLua/Core/ToLua.cs:158)
LuaInterface.LuaDLL:lua_pcall(IntPtr, Int32, Int32, Int32)
LuaInterface.LuaStatePtr:LuaPCall(Int32, Int32, Int32) (at Assets/LuaFramework/ToLua/Core/LuaStatePtr.cs:374)
LuaInterface.LuaState:LuaLoadBuffer(Byte[], String) (at Assets/LuaFramework/ToLua/Core/LuaState.cs:2141)
LuaInterface.LuaState:DoFile(String) (at Assets/LuaFramework/ToLua/Core/LuaState.cs:616)
LuaInterface.LuaState:OpenBaseLuaLibs() (at Assets/LuaFramework/ToLua/Core/LuaState.cs:207)
LuaInterface.LuaState:Start() (at Assets/LuaFramework/ToLua/Core/LuaState.cs:217)
LuaFramework.LuaManager:InitStart() (at Assets/LuaFramework/Scripts/Manager/LuaManager.cs:26)
LuaFramework.GameManager:OnInitialize() (at Assets/LuaFramework/Scripts/Manager/GameManager.cs:240)
LuaFramework.GameManager:<OnResourceInited>m__2() (at Assets/LuaFramework/Scripts/Manager/GameManager.cs:231)
LuaFramework.<Initialize>c__AnonStoreyE:<>m__4(Object[]) (at Assets/LuaFramework/Scripts/Manager/ResourceManager.cs:45)
LuaFramework.<OnLoadAsset>c__Iterator2`1:MoveNext() (at Assets/LuaFramework/Scripts/Manager/ResourceManager.cs:139)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by gengzhendong** [comment]
我也出现这个问题，问题处在Print函数，在lua函数名的时候返回为空，导致索引出错，目前也找不到原因

**Comment by bsyx** [comment]
@jarjin @jarjin2000  这个原因大家都解决不到了,帮大家看一下。

**Comment by bsyx** [comment]
这个问题应该是从tolua1.0.6开始就有了,目前我用的以下方法暂时屏蔽掉了。
![image](https://user-images.githubusercontent.com/7437205/34416289-d1ad6324-ec2d-11e7-8613-9ae487b25e1c.png)

希望作者早点把这个存在了很久的BUG修复掉。

**Comment by jarjin** [comment]
好的，最近有点忙，我晚上看下

**Comment by jarjin** [comment]
bug已修复，如果不想更新代码，请在luajit 打bytecode的时候带-g参数，以保留调试信息。
