### ISSUE TITLE
无法在 Unity 2017.3.0 上使用

### ISSUE THREAD

**Issue by TristenChenTao** [jarjin/LuaFramework_UGUI#41]
LuaFramework_UGUI 版本：更新tolua#到1.0.7.386版

在 Build X Resource 时，提示如下错误：

Assets/LuaFramework/ToLua/Source/Generate/UnityEngine_TextureWrap.cs(354,34): error CS1061: Type `UnityEngine.Texture' does not contain a definition for `imageContentsHash' and no extension method `imageContentsHash' of type `UnityEngine.Texture' could be found. Are you missing an assembly reference?

Assets/LuaFramework/ToLua/Source/Generate/UnityEngine_TextureWrap.cs(594,8): error CS1061: Type `UnityEngine.Texture' does not contain a definition for `imageContentsHash' and no extension method `imageContentsHash' of type `UnityEngine.Texture' could be found. Are you missing an assembly reference?

Assets/LuaFramework/ToLua/Source/Generate/UnityEngine_WWWWrap.cs(356,16): error CS0234: The type or namespace name `MovieTexture' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?

Assets/LuaFramework/ToLua/Source/Generate/UnityEngine_WWWWrap.cs(357,24): error CS0841: A local variable `o' cannot be used before it is declared

Error building Player because scripts had compiler errors

希望能提供技术支持，我在 CustomSettings 中注释掉 _GT(typeof(Texture)), 依然报错，谢谢

**Comment by jarjin** [comment]
你上面报错由于之前先在低版本生成Wrap，再在Unity 2017.3.0打开导致，是Unity的版本API变化，与框架无关。
