### ISSUE TITLE
unity2018.2.6上无法打出资源文件

### ISSUE THREAD

**Issue by chenchanLau** [jarjin/LuaFramework_UGUI#53]
unity2018.2.6上无法打出所有的StreamingAssets资源文件，只有生成部分lua的代码（3rd文件夹下），其余都没有；在unity5.6.5上则没有问题。

**Comment by chenchanLau** [comment]
打包的时候Property or indexer `UnityEngine.QualitySettings.streamingMipmapsRenderersPerFrame' cannot be assigned to (it is read-only)

**Comment by GITHUB243884919** [comment]
我跟你一样的问题，解决没？

**Comment by 843402802** [comment]
https://blog.csdn.net/ChinarCSDN/article/details/96652257 tolua常见错误解决，楼主应该搞定了，这个就留给后面的人看吧。
